//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StokTakipOtomasyonu.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Markalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Markalar()
        {
            this.Urunler = new HashSet<Urunler>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "Kategori Adý Boþ Geçilemez")]
        [Display(Name = "Kategori Adý")]
        public int KategoriID { get; set; }

        [Required(ErrorMessage = "Açýklama Alaný Boþ Geçilemez")]
        [Display(Name = "Açýklama")]
        public string Aciklama { get; set; }

        [Required(ErrorMessage = "Marka Adý Alaný Boþ Geçilemez")]
        [Display(Name = "Marka Adý")]
        public string Marka { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Urunler> Urunler { get; set; }
    }
}
